// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy4w2RRL5S-Fo-BGF470gV7itJLnTfOV8',
    appId: '1:472552238400:android:916766e54f6494f5bb1ea5',
    messagingSenderId: '472552238400',
    projectId: 'locationapp-6f42a',
    databaseURL: 'https://locationapp-6f42a-default-rtdb.firebaseio.com',
    storageBucket: 'locationapp-6f42a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ZrZmuAxfSQwh9-7xh-h0l4zeoW6QOhw',
    appId: '1:472552238400:ios:cd4530b20cbc8926bb1ea5',
    messagingSenderId: '472552238400',
    projectId: 'locationapp-6f42a',
    databaseURL: 'https://locationapp-6f42a-default-rtdb.firebaseio.com',
    storageBucket: 'locationapp-6f42a.appspot.com',
    iosClientId: '472552238400-pu1192i09muigukhb24bk4lhsba2olm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled2',
  );
}
